cabal-version:      3.0
name:               small-caps-converter
version:            0.1.0.0
-- synopsis:
-- description:
license:            MIT
license-file:       LICENSE
author:             andsilva1504
maintainer:         andrevazesilva@gmail.com
-- copyright:
category:           Text
build-type:         Simple
extra-doc-files:    CHANGELOG.md
-- extra-source-files:

common warnings
    ghc-options: -Wall

executable small-caps-converter
    import:           warnings
    main-is:          Main.hs
    other-modules:    Converters.TextConverter,
                      Converters.YamlConverter,
                      Core.SmallCaps
    -- other-extensions:
    -- other-extensions:
    build-depends:    base >= 4.7 && < 5,
                      yaml,
                      aeson,
                      text,
                      filepath,
                      bytestring
    hs-source-dirs:   app, src
    default-language: Haskell2010

test-suite small-caps-test
    type:             exitcode-stdio-1.0
    main-is:          Spec.hs
    other-modules:    Core.SmallCaps
    build-depends:    base >= 4.7 && < 5,
                      QuickCheck,
                      text
    hs-source-dirs:   test, src
    default-language: Haskell2010